// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $api_comment_postId_ from "./routes/api/comment/[postId].tsx";
import * as $api_comment_like_postId_commentId_ from "./routes/api/comment/like/[postId]/[commentId].tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_like_postId_ from "./routes/api/like/[postId].tsx";
import * as $api_post_index from "./routes/api/post/index.tsx";
import * as $api_upload_profile_image from "./routes/api/upload-profile-image.ts";
import * as $api_users_username_ from "./routes/api/users/[username].ts";
import * as $api_users_username_follow from "./routes/api/users/[username]/follow.ts";
import * as $api_users_username_index from "./routes/api/users/[username]/index.ts";
import * as $api_users_username_unfollow from "./routes/api/users/[username]/unfollow.ts";
import * as $api_users_index from "./routes/api/users/index.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $post_new from "./routes/post/new.tsx";
import * as $register from "./routes/register.tsx";
import * as $user_username_ from "./routes/user/[username].tsx";
import * as $AnimatedPostsList from "./islands/AnimatedPostsList.tsx";
import * as $Button from "./islands/Button.tsx";
import * as $ChatButton from "./islands/ChatButton.tsx";
import * as $CommentSection from "./islands/CommentSection.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $CreatePostForm from "./islands/CreatePostForm.tsx";
import * as $LeftSidebar from "./islands/LeftSidebar.tsx";
import * as $LikeButton from "./islands/LikeButton.tsx";
import * as $Navbar from "./islands/Navbar.tsx";
import * as $Profile from "./islands/Profile.tsx";
import * as $ProfileImageUploader from "./islands/ProfileImageUploader.tsx";
import * as $ProfileSidebar from "./islands/ProfileSidebar.tsx";
import * as $UserContext from "./islands/UserContext.tsx";
import * as $UserProfileIsland from "./islands/UserProfileIsland.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/api/comment/[postId].tsx": $api_comment_postId_,
    "./routes/api/comment/like/[postId]/[commentId].tsx":
      $api_comment_like_postId_commentId_,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/like/[postId].tsx": $api_like_postId_,
    "./routes/api/post/index.tsx": $api_post_index,
    "./routes/api/upload-profile-image.ts": $api_upload_profile_image,
    "./routes/api/users/[username].ts": $api_users_username_,
    "./routes/api/users/[username]/follow.ts": $api_users_username_follow,
    "./routes/api/users/[username]/index.ts": $api_users_username_index,
    "./routes/api/users/[username]/unfollow.ts": $api_users_username_unfollow,
    "./routes/api/users/index.ts": $api_users_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/post/new.tsx": $post_new,
    "./routes/register.tsx": $register,
    "./routes/user/[username].tsx": $user_username_,
  },
  islands: {
    "./islands/AnimatedPostsList.tsx": $AnimatedPostsList,
    "./islands/Button.tsx": $Button,
    "./islands/ChatButton.tsx": $ChatButton,
    "./islands/CommentSection.tsx": $CommentSection,
    "./islands/Counter.tsx": $Counter,
    "./islands/CreatePostForm.tsx": $CreatePostForm,
    "./islands/LeftSidebar.tsx": $LeftSidebar,
    "./islands/LikeButton.tsx": $LikeButton,
    "./islands/Navbar.tsx": $Navbar,
    "./islands/Profile.tsx": $Profile,
    "./islands/ProfileImageUploader.tsx": $ProfileImageUploader,
    "./islands/ProfileSidebar.tsx": $ProfileSidebar,
    "./islands/UserContext.tsx": $UserContext,
    "./islands/UserProfileIsland.tsx": $UserProfileIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
